---
- hosts: localhost

  vars_files:
    - vars.yml

  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/git.yml
    - include: tasks/jdk.yml
    - include: tasks/intellijidea.yml
