---
- name: install dependencies
  become: yes
  package:
    name: '{{ packages }}'
  vars:
    packages:
      - libcanberra-gtk-module

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ intellij_download_dir }}'

- name: stat install dir
  stat:
    path: '{{ intellij_install_dir }}/bin'
  register: stat_install_dir

- name: download IntelliJ IDEA
  get_url:
    url: '{{ intellij_mirror }}/{{ intellij_redis_filename }}'
    dest: '{{ intellij_download_dir }}/{{ intellij_redis_filename }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    timeout: '{{ intellij_idea_download_timeout_seconds }}'
    mode: 'u=rw,go=r'
  when: not stat_install_dir.stat.exists

- name: create IntelliJ IDEA installation directory
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ intellij_install_dir }}'

- name: install IntelliJ IDEA
  unarchive:
    src: '{{ intellij_download_dir }}/{{ intellij_redis_filename }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    dest: '{{ intellij_install_dir }}'
    owner: root
    group: root
    creates: '{{ intellij_install_dir }}/bin'

- name: create bin link
  file:
    src: '{{ intellij_install_dir }}/bin/idea.sh'
    dest: '{{ ansible_env.HOME }}/.local/bin/idea'
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
